trigger: none
pool: InfraVM
jobs:
- job: build
  displayName: buildinfra
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'ServiceVM'
      backendAzureRmOverrideSubscriptionID: 'b35c9afa-9045-49a7-852b-e7bffe5ca332'
      backendAzureRmResourceGroupName: 'kolkata-resource'
      backendAzureRmStorageAccountName: 'kolkata7401'
      backendAzureRmContainerName: 'kolkata-container'
      backendAzureRmKey: 'kolkata.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'
- job: apply
  displayName: apply
  steps: 
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'ServiceVM'
