# Trigger disabled
trigger: none

# Agent pool (ensure this pool exists in your Azure DevOps)
pool: InfraVM

jobs:
- job: build
  displayName: buildinfra
  steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.13.2' # use specific version for stability (or 'latest' if you prefer)

    - task: TerraformTask@5
      displayName: Terraform Init (build)
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'ServiceVM'                 # Service connection name in Azure DevOps
        backendAzureRmOverrideSubscriptionID: 'b35c9afa-9045-49a7-852b-e7fbfe5ca332' # corrected ID
        backendAzureRmResourceGroupName: 'kolkata-resource'
        backendAzureRmStorageAccountName: 'kolkata7401'
        backendAzureRmContainerName: 'kolkata-container'
        backendAzureRmKey: 'kolkata.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate (build)
      inputs:
        provider: 'azurerm'
        command: 'validate'

- job: Install
  displayName: Terraform Install
  steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform (install job)
      inputs:
        terraformVersion: '1.13.2' # keep same version as build job

    - task: TerraformTask@5
      displayName: Terraform Init (install)
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'ServiceVM'
        backendAzureRmOverrideSubscriptionID: 'b35c9afa-9045-49a7-852b-e7fbfe5ca332'
        backendAzureRmResourceGroupName: 'kolkata-resource'
        backendAzureRmStorageAccountName: 'kolkata7401'
        backendAzureRmContainerName: 'kolkata-container'
        backendAzureRmKey: 'kolkata.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Apply (install)
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'ServiceVM'
